name: Севастопольский Особой Категории Снабжения Музей-Заповедник Федеральной Культуры
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title/

url: http://pamuq.github.io/sevmuseum
# Uncomment for local testing
#url: http://127.0.0.1:4000

author:
    name: Pamuq Araştırıcı
    twitter: #sevastopol_info